import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import Navbar from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Consultant Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <header>
            <SignedOut >
            </SignedOut>
            <SignedIn >
              <Navbar />
            </SignedIn>
          </header>
          <main>{children}</main>
        </body>
      </ClerkProvider>
    </html>
  );
}
