options:
  logging: CLOUD_LOGGING_ONLY  # Use only Cloud Logging for build logs

steps:
  # Step 1: Build the Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'  # Specify the frontend folder where your Dockerfile is
    args: [
      'build',
      '--build-arg', 'VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}',
      '--build-arg', 'VITE_BACKEND_URL=${VITE_BACKEND_URL}',
      '-t', 'gcr.io/$PROJECT_ID/consultant-tracker-client:latest',
      '.'
    ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/consultant-tracker-client:latest'
    ]

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'consultant-tracker-client',
      '--image', 'gcr.io/$PROJECT_ID/consultant-tracker-client:latest',
      '--region', 'europe-north1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY},VITE_BACKEND_URL=${VITE_BACKEND_URL}'
    ]
