version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - POSTGRES_USER=ct
      - POSTGRES_PASSWORD=ct
      - POSTGRES_DB=ct
    volumes:
      - ./data/pgdata:/var/lib/postgresql/ct
    ports:
      - 5432:5432
    restart: always