import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {TableContextProvider} from "@/context/context";
import {DetailsContextProvider} from "@/context/details";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Consultant Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <TableContextProvider>
      <DetailsContextProvider>
        <body className={inter.className}>{children}</body>
      </DetailsContextProvider>
    </TableContextProvider>
    </html>
  );
}
