import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {TableContextProvider} from "@/context/table";
import {DetailsContextProvider} from "@/context/details";


export const metadata: Metadata = {
  title: "Consultant Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <TableContextProvider>
      <DetailsContextProvider>
        <body>{children}</body>
      </DetailsContextProvider>
    </TableContextProvider>
    </html>
  );
}
