app:
  mode:
spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
  sql:
    init:
      platform: postgresql
      mode: never
  config:
    import: optional:secret.yml
  main:
    allow-circular-references: true