app:
  mode:
server:
  port: 8080
spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          audiences: api://default
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql
      mode: always
  config:
    import: optional:secret.yml
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
