app:
  mode:
server:
  port: 8080
spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  security:
    oauth2:
      client:
        registration:
          clerk:
            client-id: ${CLERK_CLIENT_ID}
            client-secret: ${CLERK_CLIENT_SECRET_KEY}
       #   jwt:
        #    issuer-uri: https://dev-34582620.okta.com/oauth2/default   -- example
         #   audiences: api://default   -- example
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql
      mode: always
  config:
    import: optional:secret.yml
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework:
        security: TRACE
