app:
  mode: demo
spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql
      mode: always
      data-locations: classpath:data-demo.sql
  config:
    import: optional:secret.yml
  main:
    allow-circular-references: true
