name: Deploy website

on:
  push:
    branches:
      - main

env:
  VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
  VITE_BACKEND_URL: ${{secrets.VITE_BACKEND_URL}}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: cd frontend && npm i

      - name: Build project
        run: cd frontend && npm run build

      - name: Show folders after build
        run: cd frontend && ls -la

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Show folders before downloading artifact
        run: ls -la

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./frontend/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist # deploy src folder