#name: Deploy frontend to Google Cloud Run
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    # Step 1: Checkout the code
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    # Step 2: Authenticate to Google Cloud
#    - name: Set up Google Cloud SDK
#      uses: google-github-actions/setup-gcloud@v1
#      with:
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        service_account_key: ${{ secrets.GCP_SA_KEY }}
#        export_default_credentials: true
#
#    # Step 3: Trigger Cloud Build
#    - name: Trigger Cloud Build
#      run: |
#        gcloud builds submit --config=cloudbuild.yaml \
#          --substitutions=_VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }},_VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}

name: Deploy

on:
  push:
    branches:
      - main

env:
  VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
  VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name:
        uses: cd frontend

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./frontend/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist