#name: Deploy frontend to Google Cloud Run
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    # Step 1: Checkout the code
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    # Step 2: Authenticate to Google Cloud
#    - name: Set up Google Cloud SDK
#      uses: google-github-actions/setup-gcloud@v1
#      with:
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        service_account_key: ${{ secrets.GCP_SA_KEY }}
#        export_default_credentials: true
#
#    # Step 3: Trigger Cloud Build
#    - name: Trigger Cloud Build
#      run: |
#        gcloud builds submit --config=cloudbuild.yaml \
#          --substitutions=_VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }},_VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}

name: Consultant tracker frontend deployment to GP

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]
  workflow_dispatch:


env:
  VITE_CLERK_PUBLISHABLE_KEY: ${{secrets.VITE_CLERK_PUBLISHABLE_KEY}}
  VITE_BACKEND_URL: ${{secrets.VITE_BACKEND_URL}}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd frontend && npm i

      - name: Build the react app
        run: cd frontend && npm run build

      - name: setup pages
        uses: actions/configure-pages@v3
        with:
          enablement: true

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: frontend/dist

      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v2